source 'https://rubygems.org'
gem 'github-pages', '109', group: :jekyll_plugins
gem 'jekyll', '3.3.1'
gem 'jekyll-sass-converter', '1.3.0'
gem 'kramdown', '1.11.1'
gem 'liquid', '3.0.6'
gem 'rouge', '1.11.1'
gem 'github-pages-health-check', '1.3.0'
gem 'jekyll-redirect-from', '0.11.0'
gem 'jekyll-sitemap', '0.12.0'
gem 'jekyll-feed', '0.8.0'
gem 'jekyll-gist', '1.4.0'
gem 'jekyll-paginate', '1.1.0'
gem 'jekyll-coffeescript', '1.0.1'
gem 'jekyll-seo-tag', '2.1.0'
gem 'jekyll-github-metadata', '2.2.0'
gem 'jekyll-avatar', '0.4.2'
gem 'jemoji', '0.7.0'
gem 'jekyll-mentions', '1.2.0'
gem 'jekyll-relative-links', '0.2.1'
gem 'jekyll-optional-front-matter', '0.1.2'
gem 'jekyll-readme-index', '0.0.3'
gem 'jekyll-default-layout', '0.1.4'
gem 'jekyll-titles-from-headings', '0.1.2'
gem 'listen', '3.0.6'
gem 'activesupport', '4.2.7'
gem 'minima', '2.0.0'
gem 'jekyll-swiss', '0.4.0'
gem 'jekyll-theme-primer', '0.1.1'
gem 'jekyll-theme-minimal', '~> 0.0.3'
